### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by beabout** [reedhersma/BCdjango#1]
Follow the guide [here](https://docs.djangoproject.com/en/4.1/intro/tutorial02/)

## Todo
- [x] Add Order/Product classes to `forms/models.py`
- [x] Add 'forms.apps.FormsConfig' to the `INSTALLED_APPS` array in `BandanaCoffee/settings.py`
- [x] Run `python3 manage.py makemigrations forms; python3 manage.py migrate` (this will create the Orders and Products tables)

## Vocab
**Database Schema:** A map of the tables and table fields for a given database
**Database Migration:** A change to a database schema

**Comment by beabout** [comment]
@reedhersma I don't think it is a good idea to call this application `forms`. Lots of languages have "Reserved Keywords" (see Python's [here](https://flexiple.com/python/python-reserved-words/)). You're program will fail if you try to use these words out of context. While `forms` is not a Reserved Keyword in Python, it is part of Django's vocabulary (see [here](https://docs.djangoproject.com/en/4.1/topics/forms/#the-django-form-class)). Before we run those migration commands, consider a different name to encompass the Order, Products (and maybe eventually Subscription) classes. It might be fine to change it from `forms` to `orders` even if we have an Order class as well. 

Once that's done, you're OK to run those migration commands whenever you'd like. After you do, run `python3 manage.py runserver` to make sure there isn't any errors. Then close this out if all is good. Post any errors you see below if you can't figure them out
