### ISSUE TITLE
CSS!

### ISSUE THREAD

**Issue by beabout** [reedhersma/BCdjango#10]
Your website looks like doodoo. So we'll spice it up with some styles from CSS. 

_Cascading Style Sheets (CSS)_ is a stylesheet language used to describe the presentation of a document written in HTML or XML.

Tutorial [here](https://docs.djangoproject.com/en/4.1/intro/tutorial06/#customize-your-app-s-look-and-feel)

## Todo

- [x] Create `sales/static` directory. 
- [x] Create `sales/static/sales` directory.
- [x] Create `sales/static/sales/style.css`
- [x] Add some initial styling to `style.css` like `body { background: yellow; }`
- [x] Include styles in a view like below

```html
{% load static %}
<link rel="stylesheet" href="{% static 'sales/style.css' %}">
```

**Comment by reedhersma** [comment]
I think I completed these as described. I think when I'm trying the Python3 manage.py runserver I'm getting more version errors.
