### ISSUE TITLE
Create A Form View (index.html)

### ISSUE THREAD

**Issue by beabout** [reedhersma/BCdjango#2]
Follow the guide starting [here](https://docs.djangoproject.com/en/4.1/intro/tutorial03/#writing-more-views)

## Todo
- [x] Add `from . import views` at the top of `forms/urls.py` (this is necessary so we can access the `views` object in the bullet point below this
- [x] Add `path('', views.index, name='index'),` to the `INSTALLED_APPS` array in `forms/urls.py`
- [x] Add `from . models import Submission, Product` to the top of `forms/views.py` (this imports the Submission and Product classes so we can access it later in the file) 
- [x] Beef up the index function in `forms/views.py`. Look at **index() modifications**
- [x] Add `forms/templates/forms/index.html` (you'll have to create a templates folder, then a forms folder, then a index.html). Add the content under **index.html additions** into `index.html`

### index() modifications

```python
# in forms/views.py
def index(request):
    products = Product.objects.all()
    return HttpResponse(products)
```
### index.html additions

```html
<div>
  <h1>Would you like some Coffee?</h1>
  <p>submit your order below</p>
</div>
```
